### ISSUE TITLE
[BUG] AirPod pro 2 1562AE Can't connect both iPhone 15 pro max and Macbook pro M1 2020

### ISSUE THREAD

**Issue by phucanh08** [TowyTowy/airreps#43] opened 2023-11-12 08:55 UTC
### Current Behavior

Device: MacBook Pro M1 2020 use macOS Sonoma 14.1.1, iPhone 15 Pro Max use iOS 17.1.1
=> AirPod pro 2 1562AE Can't connect both iPhone 15 pro max and Macbook pro M1 2020

### Expected Behavior

=> AirPod pro 2 1562AE can connect both iPhone 15 pro max and Macbook pro M1 2020

### Steps To Reproduce

1. Connect AirPod pro 2 1562AE with iPhone
2. Can't connect with MacBook use the same iCloud.

Or
1. Connect AirPod with MacBook 
2. Can't connect with iPhone use the same iCloud.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.

**Comment by TowyTowy** [comment] 2023-11-12 10:47
This is not a bug with the guide. Closing.

**Closed** 2023-11-12 10:47 UTC
Labels: bug
